version: "3.9"
services:
  backend:
    build: ./backend
    container_name: cv-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    restart: always

